#!/usr/bin/env python
"""
WordAPI.py
Copyright 2012 Wordnik, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os

from models import *


class AsheApi(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    
    def query(self, soc, **kwargs):
        """

        Args:
            soc, int: The SOC code. (required)
            filters, str: You may filter on single values, like 'gender:2|age:40 (optional)
            
        Returns: 
        """

        allParams = ['soc', 'filters']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method query" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/ashe/estimate'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}

        if ('soc' in params):
            queryParams['soc'] = self.apiClient.toPathValue(params['soc'])
        if ('filters' in params):
            queryParams['filters'] = self.apiClient.toPathValue(params['filters'])
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        
        
    def getFilterInfo(self, name, **kwargs):
        """Get information about a specific filter.

        Args:
            name, str: The name of the filter. (required)
            
        Returns: ASHEFilterInfo
        """

        allParams = ['name']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getFilterInfo" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/ashe/filter/{name}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}

        if ('name' in params):
            replacement = str(self.apiClient.toPathValue(params['name']))
            resourcePath = resourcePath.replace('{' + 'name' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'ASHEFilterInfo')
        return responseObject
        
        
    def getFilterNames(self, **kwargs):
        """Get a list of all available filter names.

        Args:
            
        Returns: list[str]
        """

        allParams = []

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getFilterNames" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/ashe/filters'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}

        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'list[str]')
        return responseObject
        
        
    def getFilterNames(self, **kwargs):
        """Get a list of all available filter names.

        Args:
            
        Returns: list[ASHEFilterInfo]
        """

        allParams = []

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getFilterNames" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/ashe/filters/all'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}

        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'list[ASHEFilterInfo]')
        return responseObject
        
        
    


