#!/usr/bin/env python
"""
WordAPI.py
Copyright 2012 Wordnik, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os

from models import *


class SocApi(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    
    def getSOCInfo(self, code, **kwargs):
        """Get information about a particular SOC code.

        Args:
            code, int: The SOC code. (required)
            
        Returns: SOCInfo
        """

        allParams = ['code']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getSOCInfo" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/soc/code/{code}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}

        if ('code' in params):
            replacement = str(self.apiClient.toPathValue(params['code']))
            resourcePath = resourcePath.replace('{' + 'code' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'SOCInfo')
        return responseObject
        
        
    def find(self, q, **kwargs):
        """Find SOC codes by keywords - pretty much like googling it.

        Args:
            q, str: Search string. (required)
            
        Returns: list[SOCInfo]
        """

        allParams = ['q']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method find" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/soc/search'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}

        if ('q' in params):
            queryParams['q'] = self.apiClient.toPathValue(params['q'])
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'list[SOCInfo]')
        return responseObject
        
        
    


